app:
  delimiter: '=========================='
  version: '@project.version@'

spring:
  application:
    name: api-dnd-service
  profiles:
    active: dev
#    active: prod

  messages:
    always-use-message-format: false
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: true

#Open-api
springdoc:
  api-docs:
    path: /dnd-docs

#Prometheus
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,loggers
      base-path: /api/dnd/info
  metrics:
    enable:
      jvm: true